MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  WEIGHT: "/home/hl/hl/ourMetaWithoutFPN/voc0712_split_2_base_pretrained.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 8
    NUM_CLASSES: 21
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    # FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractorPrototypeLoss"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("voc_2007_trainval_10shot_standard", "voc_2012_trainval_10shot_standard")
  CLOSEUP: ("voc_2007_trainval_10shot_closeup_standard", "voc_2012_trainval_10shot_closeup_standard")
  TEST: ("voc_2007_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (2600, 3400)
  MAX_ITER: 4000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
oneStageOrtwo:
  oneStage: False
marginLoss:
  gamma: 2.0
  margin: 10.0
CLASSSPILT:
  spilt: 2
