MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "/home/hl/hl/ourMetaWithoutFPN/model_final_standard_shot1;3.0_0.0.pth"
  WEIGHT: "/home/hl/hl/ourMetaWithoutFPN/coco_10shot_base_pretrained.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 81
    POOLER_RESOLUTION: 8
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractorPC_PSLoss"
    # FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractorSpatialGAP_128"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("coco_2014_train_10shot_standard", "coco_2014_val_10shot_standard")
  CLOSEUP: ("coco_2014_10shot_closeup_standard",)
  TEST: ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (5600, 7000)
  MAX_ITER: 8000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
oneStageOrtwo:
  oneStage: False
marginLoss:
  gamma: 10.0
  margin: 10.0
CLASSSPILT:
  spilt: 10